name: java full jar file
on:
    release:
        types: [created]
jobs:
    build:
        name: java file/jar
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: publish
              uses: actions/upload-artifact@v2
              with:
                name: build
                path: build/libs/*.jar
                retention-days: 0
                if-no-files-found: error
            - name: publish
              uses: actions/upload-artifact@v2
              with:
                name: build
                path: build/libs/*.jar
                retention-days: 0
